blueprint:
  name: Doorbell Notification
  description: >
    **Version: 0.1**
    This blueprint sends notification to mobile device when the doorbell is ringed
    
  domain: automation
  input:
    doorbell_sensor:
      name: Doorbell Sensor *
      description: The sensor associated with the doorbell ringing
      selector:
        entity:
          domain: sensor
    device_id:
      name: DeviceID *
      description: The DeviceID associated with the mobile phone
      selector:
        text:
        
variables:
  doorbell_sensor: !input doorbell_sensor
  device_id: !input device_id

trigger:
  - platform: state
    entity_id: !input doorbell_sensor
    to: "ringing"

action:
  - service: persistent_notification.create
    data:
      title: "Someone is at the door!"
      message: "Someone ringed the doorbell"
  - service: notify.mobile_app_!input device_id
    data:
      message: "Someone ringed the doorbell"
